---
title: "Project 03 Presentation"
author: "Gabrielle Bartomeo, Binish Chandry, Zach Dravis, Burcu Kaniskan, Niteen Kumar, Betsy Rosalen"
date: "March 22, 2018"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Question 1

We start with exploring the resources utilized by Kaggle survey users for learning data science. Where do they look for learning, what data sets do they use, and is there significant variance with these between survey takers of different educational standings?

## Question 2

Next, we examine what these survey takers of various educational backgrounds find themselves excited to learn. Due to the ever-evolving nature of technology and, by extension, data science, it is imperative that they remain relevant in their field and are passionate in their pursuit for relevance.

## Question 3

Furthermore, does their educational level or job title factor into their process and productivity, such as which data science methods they favor, or the length of time they work with data?

## Question 4

Those who are new to data science and those who are employed in the field of the survey takers may have different opinions and experiences with which languages are most important to learn and which are being used. Alternatively, they might be in complete agreement.

## Question 5

The most frequently used of the programming languages are R and Python. But are these in agreement as well? Do those survey takers feel that others should first and foremost study the languages they themselves have taken up, or perhaps with their insight, know to suggest the language of the two they themselves did not learn?

## Question 6

Lastly, true to the word "value," considerations have to be made regarding pay. The compensation received by survey takers for their work in either R or Python needs quantification to discover which language earns a data scientist more overall and in general.
